version: '3.1'

services:

  bitblog:
    image: theoafactor/bitblog:123
    restart: always
    depends_on:
      - mysql
    ports:
      - 74:80

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password


  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_HOST=mysql
      - PMA_PORT=3306

